Revert "tests: Adopt private require() for skins.minerva.scripts"
This reverts commit 548e94da982ca9f882eb9c42869540456f0c9d9f.

Reason for revert: The patch was causing the following error on pageload

    Error: Cannot require undefined file includes/Skins/ToggleList/ToggleList.js
    require startup.js:1006

Bug: T373482
Change-Id: I22751109c124795af7d2e0ad6c4104745b2d6632